// Populated mock dataset for the UI screenshot harness.
// Shapes follow crates/sigillum-api/src/response.rs, the UI's
// crates/sigillum-daemon/ui/src/contracts.ts, and the parsing in ui/src/views/*.
// When the daemon or UI contracts evolve, update the affected export here —
// the driver renders whatever this file returns, so stale shapes show up as
// empty cards in the shots.

export const NOW = Math.floor(Date.now() / 1000);
const H = 3600;
const D = 24 * H;

// decimal ETH string -> wei hex
export function eth(v) {
  const [a, b = ""] = String(v).split(".");
  const wei = BigInt(a + (b + "0".repeat(18)).slice(0, 18));
  return "0x" + wei.toString(16);
}
// decimal token units -> hex with given decimals
export function tok(v, decimals = 6) {
  const [a, b = ""] = String(v).split(".");
  const units = BigInt(a + (b + "0".repeat(decimals)).slice(0, decimals));
  return "0x" + units.toString(16);
}

export const ADDR = {
  opsHot: "0x3f5cE5fBFe3e9af3971dd833d26ba9b5c936f0be",
  opsTreasury: "0x8Ba1f109551bd432803012645ac136ddd64DBa72",
  opsRecv0: "0x71C7656EC7ab88b098defB751B7401B5f6d8976F",
  opsRecv1: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30",
  watch0: "0x9e3d5aF71B02C94A96F4E9b0c6E1B4d2A8f5C7e1",
  watch1: "0x1aD91ee08f21bE3dE0BA2ba6918E714dA6B45836",
  base0: "0xBE0eB53F46cd790Cd13851d5EFf43D12404d33E8",
  arb0: "0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF",
  acmeSweep: "0x53d284357ec70cE289D6D64134DfAc8E511c8a3D",
  stealthA: "0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf",
  stealthB: "0xd25b4A8F3C33d8F36b0D6B5c0E51E7E18D6f6a42",
  stealthC: "0x4A6f8B2c9D1e3F5a7B9c0d2E4f6A8b0C1d3E5f70",
  usdc: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  usdt: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  router: "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD",
  mixer: "0x8589427373D6D84E98730D7795D8f6f8731FDA16",
};

const XPUB_OPS =
  "xpub6CUGRUonZSQ4TWtTMmzXdrXDtypWKiKrhko4egpiMZbpKQLYch1wR6rVH2K9y3b7J8uQ1oGf4LkM3nN5pP7qR9sT2u";
const XPUB_WATCH =
  "xpub6BosfCnifzxcFwrSzQiqu2DBVTshkCXacvNsWGYJVVhhawA7d4R5WSWGFNbi8Aw6ZRc1brxMyWMzG3DSSSSoekkudhUd9yLb6qx39T9nMdj";
export const STEALTH_META_ADDRESS =
  "st:eth:0x02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9:0x03a34b99f22c790c4e36b2b3c2c35a36db06226e41c692fc82b8b56ac1c540c5bd";

// /api/compartment/list entries (CompartmentInfo in response.rs).
export const COMPARTMENTS = [
  { id: 1, label: "operations", threshold: 2, passphrase_mode: null, is_active: true },
  { id: 2, label: "cold reserve", threshold: 3, passphrase_mode: null, is_active: false },
];

// Status/unlock payloads carry the lightweight UnlockedCompartment shape
// (id/label/threshold/passphrase_mode), not the CompartmentInfo list shape.
export const UNLOCKED_COMPARTMENTS = [
  { id: 1, label: "operations", threshold: 2, passphrase_mode: null },
];

export const statusFor = (mode) => {
  if (mode === "setup") {
    return { initialized: false, locked: true, unlocked_compartments: [] };
  }
  if (mode === "locked") {
    return { initialized: true, locked: true, unlocked_compartments: [] };
  }
  return {
    initialized: true,
    locked: false,
    // ActiveCompartment in response.rs: the shell reads
    // compartment_id/compartment_label for the badge and the counts for the
    // overview hero stats.
    active_compartment: {
      compartment_id: 1,
      compartment_label: "operations",
      api_key_count: 2,
      secret_count: 3,
    },
    unlocked_compartments: UNLOCKED_COMPARTMENTS,
  };
};

export const unlockResponse = {
  status: "unlocked",
  method: "passphrase",
  cascading: false,
  session_token: "ui-shots-session-token",
  unlocked_compartments: UNLOCKED_COMPARTMENTS,
  active_compartment_id: 1,
};

export const evmProfiles = [
  {
    name: "mainnet-llama",
    rpc_url: "https://eth.llamarpc.com",
    chain_id: 1,
    compartment_id: 1,
    auth_token_key: null,
    erc20_gas_limit: 90000,
    fee_estimation_enabled: true,
  },
  {
    name: "base-alchemy",
    rpc_url: "https://base-mainnet.g.alchemy.com/v2/••••••",
    chain_id: 8453,
    compartment_id: 1,
    auth_token_key: "alchemy_base_key",
    erc20_gas_limit: 120000,
    fee_estimation_enabled: false,
  },
];

export const seedProfiles = [
  {
    name: "ops-seed",
    label: "Operations hot wallet",
    project_account: 0,
    provider_profile: "mainnet-llama",
    compartment_id: 1,
    chain_id: 1,
    word_count: 12,
    mnemonic_secret_key: "ops_seed_mnemonic",
    account_path: "m/44'/60'/0'",
    receive_path: "m/44'/60'/0'/0",
    receive_xpub: XPUB_OPS,
    first_receive_address: ADDR.opsRecv0,
    default_destination_address: ADDR.opsTreasury,
    control_xpub: null,
    sponsor_address: null,
    hot_address: ADDR.opsHot,
    treasury_address: ADDR.opsTreasury,
    execution_enabled: true,
  },
  {
    name: "treasury-seed",
    label: "Cold reserve vault",
    project_account: 1,
    provider_profile: "mainnet-llama",
    compartment_id: 1,
    chain_id: null,
    word_count: 24,
    mnemonic_secret_key: "treasury_seed_mnemonic",
    account_path: "m/44'/60'/1'",
    receive_path: "m/44'/60'/1'/0",
    receive_xpub:
      "xpub6D4BDPcP2GT577Vvch3R8wDkScZWzQzMMUm3PWBMWvVpk5PgGhiM4rD9LkN2pQ6rS8tU0vW2xY4zA6cE8gI0kM",
    first_receive_address: ADDR.opsTreasury,
    default_destination_address: null,
    control_xpub: null,
    sponsor_address: null,
    hot_address: null,
    treasury_address: ADDR.opsTreasury,
    execution_enabled: false,
  },
];

export const xpubProfiles = [
  {
    name: "watchdesk-xpub",
    project_account: 2,
    provider_profile: "mainnet-llama",
    compartment_id: 1,
    chain_id: 1,
    external_receive_xpub: null,
    external_receive_path: null,
    external_account_xpub: XPUB_WATCH,
    external_account_path: "m/44'/60'/2'",
    default_destination_address: null,
    execution_enabled: false,
  },
];

export const stealthProfiles = [
  {
    name: "stealth-ops",
    wallet: "ops-seed",
    short_name: "OPS-S",
    provider_profile: "mainnet-llama",
    compartment_id: 1,
    chain_id: 1,
    default_destination_address: ADDR.opsTreasury,
  },
];

export const chainProfiles = [
  {
    name: "ethereum",
    chain_family: "evm",
    chain_id: 1,
    enabled: true,
    native_symbol: "ETH",
    native_decimals: 18,
    finality_blocks: 12,
    dormancy_block_window: 7200,
    permit2_address: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    uniswap_v2_router_address: null,
    provider_profile: "mainnet-llama",
    explorer_url: "https://etherscan.io",
    capabilities: ["erc20", "erc721", "erc1155", "permit2", "stealth"],
    source: "builtin",
    builtin: true,
    created_at_unix: NOW - 40 * D,
    updated_at_unix: NOW - 40 * D,
  },
  {
    name: "base",
    chain_family: "evm",
    chain_id: 8453,
    enabled: true,
    native_symbol: "ETH",
    native_decimals: 18,
    finality_blocks: 32,
    dormancy_block_window: 19200,
    permit2_address: "0x000000000022D473030F116dDEE9F6B43aC78BA3",
    uniswap_v2_router_address: null,
    provider_profile: "base-alchemy",
    explorer_url: "https://basescan.org",
    capabilities: ["erc20", "erc721"],
    source: "operator",
    builtin: false,
    created_at_unix: NOW - 12 * D,
    updated_at_unix: NOW - 12 * D,
  },
  {
    name: "arbitrum-one",
    chain_family: "evm",
    chain_id: 42161,
    enabled: false,
    native_symbol: "ETH",
    native_decimals: 18,
    finality_blocks: 24,
    dormancy_block_window: 7200,
    permit2_address: null,
    uniswap_v2_router_address: null,
    provider_profile: null,
    explorer_url: "https://arbiscan.io",
    capabilities: ["erc20"],
    source: "builtin",
    builtin: true,
    created_at_unix: NOW - 40 * D,
    updated_at_unix: NOW - 40 * D,
  },
];

export const inventoryAddresses = [
  {
    id: "addr-ops-0-1",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv0,
    derivation_path: "m/44'/60'/0'/0/0",
    derivation_pattern: "m/44'/60'/0'/0/{index}",
    account_index: 0,
    address_index: 0,
    activity_state: "funded",
    native_balance_wei_hex: eth("0.842"),
    transaction_count: 17,
    last_activity_block: 22970411,
    classifications: ["signer_available", "gas_available"],
    source: "scan",
    first_seen_at_unix: NOW - 60 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
  {
    id: "addr-ops-1-1",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    derivation_pattern: "m/44'/60'/0'/0/{index}",
    account_index: 0,
    address_index: 1,
    activity_state: "funded",
    native_balance_wei_hex: eth("0.392"),
    transaction_count: 9,
    last_activity_block: 22954180,
    classifications: ["signer_available", "token_holding", "approval_exposure"],
    source: "scan",
    first_seen_at_unix: NOW - 45 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
  {
    id: "addr-ops-base-0",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "base-alchemy",
    chain_id: 8453,
    address: ADDR.base0,
    derivation_path: "m/44'/60'/0'/0/0",
    derivation_pattern: "m/44'/60'/0'/0/{index}",
    account_index: 0,
    address_index: 0,
    activity_state: "active",
    native_balance_wei_hex: eth("0.0412"),
    transaction_count: 23,
    last_activity_block: 32881104,
    classifications: ["signer_available", "token_holding"],
    source: "scan",
    first_seen_at_unix: NOW - 30 * D,
    last_checked_at_unix: NOW - 3 * H,
  },
  {
    id: "addr-watch-0",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch0,
    derivation_path: "m/44'/60'/2'/0/0",
    derivation_pattern: "m/44'/60'/2'/0/{index}",
    account_index: 2,
    address_index: 0,
    activity_state: "funded",
    native_balance_wei_hex: eth("0.0"),
    transaction_count: 41,
    last_activity_block: 22961002,
    classifications: ["watch_only", "token_holding", "nft_holding"],
    source: "scan",
    first_seen_at_unix: NOW - 55 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
  {
    id: "addr-watch-1",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch1,
    derivation_path: "m/44'/60'/2'/0/1",
    derivation_pattern: "m/44'/60'/2'/0/{index}",
    account_index: 2,
    address_index: 1,
    activity_state: "empty",
    native_balance_wei_hex: eth("0.0"),
    transaction_count: 2,
    last_activity_block: 22104410,
    classifications: ["watch_only", "dormant_candidate"],
    source: "scan",
    first_seen_at_unix: NOW - 50 * D,
    last_checked_at_unix: NOW - 26 * H,
  },
  {
    id: "addr-ops-arb-0",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 42161,
    address: ADDR.arb0,
    derivation_path: "m/44'/60'/0'/0/0",
    derivation_pattern: "m/44'/60'/0'/0/{index}",
    account_index: 0,
    address_index: 0,
    activity_state: "empty",
    native_balance_wei_hex: eth("0.0"),
    transaction_count: 0,
    last_activity_block: null,
    classifications: ["signer_available", "empty_candidate"],
    source: "scan",
    first_seen_at_unix: NOW - 20 * D,
    last_checked_at_unix: NOW - 26 * H,
  },
];

// Holdings are separate inventory resources on the daemon wire. Keeping
// them populated makes the Portfolio shot exercise amount formatting,
// token/NFT labels, and privacy/risk grouping instead of an accidental
// addresses-only empty state.
export const inventoryHoldings = [
  {
    id: "holding-usdc-ops-1",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    asset_kind: "erc20",
    asset_address: ADDR.usdc,
    amount_hex: tok("1250.00"),
    source: "scan",
    status: "active",
    first_seen_at_unix: NOW - 45 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
  {
    id: "holding-approval-ops-1",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    asset_kind: "approval",
    asset_address: ADDR.usdc,
    counterparty_address: ADDR.router,
    protocol_address: ADDR.router,
    amount_hex: "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    source: "scan",
    status: "exposed",
    first_seen_at_unix: NOW - 14 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
  {
    id: "holding-nft-watch-0",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch0,
    derivation_path: "m/44'/60'/2'/0/0",
    asset_kind: "erc721",
    asset_address: "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85",
    token_id_hex: "0x4a3f2c91",
    metadata_uri: "ipfs://bafybeig7sigillumexample/metadata.json",
    metadata_name: "ENS name",
    spam_label: "clean",
    amount_hex: "0x1",
    source: "scan",
    status: "active",
    first_seen_at_unix: NOW - 55 * D,
    last_checked_at_unix: NOW - 2 * H,
  },
];

export const nftMetadataCache = [
  {
    chain_id: 1,
    contract_address: "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85",
    token_id_hex: "0x4a3f2c91",
    metadata_uri: "ipfs://bafybeig7sigillumexample/metadata.json",
    name: "ENS name",
    spam_label: "clean",
    spam_reasons: [],
    fetched_at_unix: NOW - 2 * H,
    fetched_uri: "https://ipfs.io/ipfs/bafybeig7sigillumexample/metadata.json",
    content_sha256: "5d8147ca4b04b2646a2f7c55cbcf131b1fe184660a3a323e05e5c36611886ac1",
    fetch_skipped_reason: null,
    updated_at_unix: NOW - 2 * H,
  },
];

export const discoveryJobs = [
  {
    id: "disc-20260714-01",
    status: "completed",
    source: "manual",
    wallet_profiles: ["ops-seed", "treasury-seed", "watchdesk-xpub"],
    provider_profiles: ["mainnet-llama", "base-alchemy"],
    chain_ids: [1, 8453],
    gap_limit: 20,
    max_index: 60,
    addresses_scanned: 180,
    active_addresses: 11,
    holdings_detected: 14,
    checkpoints: [],
    block_cursors: [
      { address: ADDR.opsRecv0, chain_id: 1, topic_family: "native", last_scanned_block: 22970411, updated_at_unix: NOW - 2 * D },
    ],
    started_at_unix: NOW - 2 * D - 3200,
    completed_at_unix: NOW - 2 * D - 2900,
    last_error: null,
  },
  {
    id: "disc-20260716-02",
    status: "running",
    source: "scheduled",
    wallet_profiles: ["watchdesk-xpub"],
    provider_profiles: ["mainnet-llama"],
    chain_ids: [1],
    gap_limit: 20,
    max_index: 120,
    addresses_scanned: 74,
    active_addresses: 4,
    holdings_detected: 6,
    checkpoints: [],
    block_cursors: [],
    started_at_unix: NOW - 1400,
    completed_at_unix: null,
    last_error: null,
  },
];

// GET /api/operations returns recent terminal and live work. The SSE
// snapshot below filters this list to live entries, matching the real
// daemon's EventsSnapshot contract.
export const operations = [
  {
    id: "op-inventory-20260716-02",
    kind: "inventory_scan_evm",
    state: "running",
    progress: { processed: 74, total: 120 },
    related_ids: ["disc-20260716-02"],
    created_at_unix: NOW - 1400,
    updated_at_unix: NOW - 90,
    completed_at_unix: null,
    error: null,
  },
  {
    id: "op-maintenance-20260716-01",
    kind: "maintenance_run",
    state: "failed",
    progress: { processed: 1, total: 3 },
    related_ids: ["stage:treasury_automation"],
    created_at_unix: NOW - 9 * H,
    updated_at_unix: NOW - 9 * H + 80,
    completed_at_unix: NOW - 9 * H + 80,
    error: "Provider authentication failed before deposit refresh; no queue jobs were broadcast.",
  },
  {
    id: "op-queue-20260715-01",
    kind: "queue_process",
    state: "completed",
    progress: { processed: 2, total: 2 },
    related_ids: [],
    created_at_unix: NOW - 28 * H,
    updated_at_unix: NOW - 28 * H + 45,
    completed_at_unix: NOW - 28 * H + 45,
    error: null,
  },
];

export const watchAddresses = [
  {
    id: "watch-01",
    address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
    label: "vitalik.eth (reference)",
    tags: ["reference", "ens"],
    source: "manual",
    enabled: true,
    created_at_unix: NOW - 90 * D,
    updated_at_unix: NOW - 90 * D,
  },
  {
    id: "watch-02",
    address: "0x28C6c06298d514Db089934071355E5743bf21d60",
    label: "Binance hot wallet 14",
    tags: ["exchange", "counterparty-flow"],
    source: "manual",
    enabled: false,
    created_at_unix: NOW - 32 * D,
    updated_at_unix: NOW - 5 * D,
  },
];

export const tokenRegistryLists = [
  {
    id: "tr-mainnet-core",
    name: "mainnet-core",
    compartment_id: 1,
    source: "import",
    entries: [
      { chain_id: 1, address: ADDR.usdc, symbol: "USDC", decimals: 6 },
      { chain_id: 1, address: ADDR.usdt, symbol: "USDT", decimals: 6 },
      { chain_id: 1, address: ADDR.weth, symbol: "WETH", decimals: 18 },
    ],
    created_at_unix: NOW - 60 * D,
    updated_at_unix: NOW - 21 * D,
  },
];

export const riskCatalog = [
  {
    address: ADDR.mixer,
    label: "Tornado Cash router (OFAC SDN)",
    risk_level: "critical",
    source: "ofac-sdn",
    notes: ["sanctioned entity", "do not interact directly"],
    created_at_unix: NOW - 120 * D,
    updated_at_unix: NOW - 120 * D,
  },
];

export const riskFindings = [
  {
    id: "risk-001",
    category: "approval_exposure",
    risk_level: "high",
    status: "open",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    subject_type: "erc20_allowance",
    subject: ADDR.router,
    source: "allowance_scan",
    recommendation: "Revoke or reduce the unlimited USDC allowance before moving funds.",
    evidence: ["Unlimited USDC allowance observed for the configured router."],
    first_seen_at_unix: NOW - 14 * D,
    last_checked_at_unix: NOW - 6 * H,
  },
  {
    id: "risk-002",
    category: "dormancy",
    risk_level: "medium",
    status: "open",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch1,
    subject_type: "wallet_address",
    subject: ADDR.watch1,
    source: "inventory",
    recommendation: "Review the dormant watch-only address and retire it if it is no longer used.",
    evidence: ["No activity observed for 41 days while prior token history remains."],
    first_seen_at_unix: NOW - 10 * D,
    last_checked_at_unix: NOW - 26 * H,
  },
  {
    id: "risk-003",
    category: "cross_party_linkage",
    risk_level: "medium",
    status: "open",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    subject_type: "receive_allocation",
    subject: "alloc-02",
    source: "receiving",
    recommendation: "Rotate the reused receive allocation before accepting another payment.",
    evidence: ["The allocation was associated with more than one counterparty."],
    first_seen_at_unix: NOW - 8 * D,
    last_checked_at_unix: NOW - 3 * D,
  },
  {
    id: "risk-004",
    category: "configuration",
    risk_level: "low",
    status: "open",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "base-alchemy",
    chain_id: 8453,
    address: ADDR.base0,
    subject_type: "provider_profile",
    subject: "base-alchemy",
    source: "selfcheck",
    recommendation: "Enable fee estimation or review the static gas defaults for Base.",
    evidence: ["Fee estimation is disabled for this provider profile."],
    first_seen_at_unix: NOW - 12 * D,
    last_checked_at_unix: NOW - 12 * D,
  },
];

export const planSteps = [
  {
    id: "step-01",
    sequence: 1,
    depends_on: [],
    action: "sweep_native",
    status: "approved",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    asset_kind: "native",
    asset_address: null,
    amount_hex: eth("0.384"),
    destination_address: ADDR.opsTreasury,
    signer_status: "available",
    simulation_status: "passed",
    simulation_evidence: ["receipt simulated at block 22970411"],
    risk_level: "low",
    blockers: [],
    auto_eligible: true,
    approved: true,
    queued_job_id: null,
  },
  {
    id: "step-02",
    sequence: 2,
    depends_on: ["step-01"],
    action: "sweep_erc20",
    status: "approved",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    asset_kind: "erc20",
    asset_address: ADDR.usdc,
    amount_hex: tok("1250.00"),
    destination_address: ADDR.opsTreasury,
    signer_status: "available",
    simulation_status: "passed",
    simulation_evidence: ["receipt simulated at block 22970411"],
    risk_level: "low",
    blockers: [],
    auto_eligible: true,
    approved: true,
    queued_job_id: null,
  },
  {
    id: "step-03",
    sequence: 3,
    depends_on: [],
    action: "revoke_erc20_approval",
    status: "review_required",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    asset_kind: "approval",
    asset_address: ADDR.usdc,
    protocol_address: ADDR.router,
    amount_hex: "0x0",
    destination_address: null,
    signer_status: "available",
    simulation_status: "not_run",
    risk_level: "medium",
    blockers: ["simulation required by policy"],
    auto_eligible: false,
    approved: false,
    queued_job_id: null,
  },
  {
    id: "step-04",
    sequence: 4,
    depends_on: [],
    action: "sweep_erc20",
    status: "review_required",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch0,
    derivation_path: "m/44'/60'/2'/0/0",
    asset_kind: "erc20",
    asset_address: ADDR.usdt,
    amount_hex: tok("412.75"),
    destination_address: ADDR.opsTreasury,
    signer_status: "watch_only",
    simulation_status: "unsupported",
    risk_level: "high",
    blockers: ["watch-only address — no signer available in this vault"],
    auto_eligible: false,
    approved: false,
    queued_job_id: null,
  },
  {
    id: "step-05",
    sequence: 5,
    depends_on: ["step-02"],
    action: "claim_reward",
    status: "review_required",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    provider_profile: "base-alchemy",
    chain_id: 8453,
    address: ADDR.base0,
    derivation_path: "m/44'/60'/0'/0/0",
    asset_kind: "reward",
    asset_address: "0x4e3Decbb3645551B8A19f0eA1678079FCB33fB4c",
    claim_adapter: "merkle-distributor",
    amount_hex: tok("18.2", 18),
    destination_address: ADDR.base0,
    signer_status: "available",
    simulation_status: "not_run",
    risk_level: "medium",
    blockers: ["claim proof not yet fetched"],
    auto_eligible: false,
    approved: false,
    queued_job_id: null,
  },
  {
    id: "step-06",
    sequence: 6,
    depends_on: [],
    action: "review_asset",
    status: "blocked",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    provider_profile: "mainnet-llama",
    chain_id: 1,
    address: ADDR.watch0,
    derivation_path: "m/44'/60'/2'/0/0",
    asset_kind: "nft",
    asset_address: "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85",
    token_id_hex: "0x4a3f2c91",
    amount_hex: "0x1",
    destination_address: null,
    signer_status: "watch_only",
    simulation_status: "unsupported",
    risk_level: "medium",
    blockers: ["manual review required", "watch-only address"],
    auto_eligible: false,
    approved: false,
    queued_job_id: null,
  },
];

export const consolidationPlans = [
  {
    id: "plan-20260715-a1",
    status: "review_required",
    chain_id: 1,
    destination_address: ADDR.opsTreasury,
    created_at_unix: NOW - 26 * H,
    updated_at_unix: NOW - 5 * H,
    summary: {
      total_steps: 6,
      blocked_steps: 1,
      review_required_steps: 3,
      approved_steps: 2,
      executable_steps: 2,
      value_items: 5,
    },
    steps: planSteps,
    policy_violations: [],
    linkage_findings: ["step-04 moves value linked to a watch-only counterparty flow"],
  },
];

export const treasuryPolicy = {
  enabled: true,
  allowed_destinations: [
    { address: ADDR.opsTreasury, label: "Treasury vault (cold reserve)" },
    { address: ADDR.opsHot, label: "Operations hot wallet" },
    { address: ADDR.acmeSweep, label: "Acme Ltd settlement" },
  ],
  max_step_native_wei_hex: eth("0.5"),
  max_plan_native_wei_hex: eth("2.0"),
  hot_floor_wei_hex: eth("0.15"),
  hot_target_wei_hex: eth("0.6"),
  hot_overflow_wei_hex: eth("1.5"),
  require_simulation: true,
  block_cross_party_linkage: true,
  allow_claim_execution: false,
  allow_gas_topups: true,
  allow_treasury_automation: false,
  max_gas_topup_wei_hex: eth("0.05"),
  allow_plan_execution: true,
  allow_sweep_execution: true,
  allow_revoke_execution: true,
  allow_exit_execution: false,
  execution_paused: false,
  max_fee_per_gas_cap_hex: "0x77359400", // 2 gwei
  simulation_freshness_secs: 900,
  created_at_unix: NOW - 40 * D,
  updated_at_unix: NOW - 4 * D,
};

export const treasuryOverview = {
  generated_at_unix: NOW - 120,
  tracked_address_count: 11,
  funded_address_count: 6,
  watch_only_address_count: 4,
  signer_address_count: 7,
  chains: [
    { chain_id: 1, native_symbol: "ETH", address_count: 7, funded_address_count: 4, native_total_wei_hex: eth("1.234") },
    { chain_id: 8453, native_symbol: "ETH", address_count: 3, funded_address_count: 2, native_total_wei_hex: eth("0.0412") },
    { chain_id: 42161, native_symbol: "ETH", address_count: 1, funded_address_count: 0, native_total_wei_hex: eth("0") },
  ],
  groups: [
    {
      wallet_family: "eth-seed",
      wallet_profile: "ops-seed",
      chain_id: 1,
      address_count: 4,
      funded_address_count: 3,
      native_total_wei_hex: eth("1.234"),
      signer_address_count: 4,
      watch_only_address_count: 0,
      erc20_holding_count: 3,
      nft_holding_count: 0,
      defi_holding_count: 1,
      claimable_holding_count: 1,
      approval_exposure_count: 1,
      dormant_candidate_count: 0,
    },
    {
      wallet_family: "eth-seed",
      wallet_profile: "ops-seed",
      chain_id: 8453,
      address_count: 2,
      funded_address_count: 2,
      native_total_wei_hex: eth("0.0412"),
      signer_address_count: 2,
      watch_only_address_count: 0,
      erc20_holding_count: 2,
      nft_holding_count: 0,
      defi_holding_count: 0,
      claimable_holding_count: 1,
      approval_exposure_count: 0,
      dormant_candidate_count: 0,
    },
    {
      wallet_family: "eth-xpub",
      wallet_profile: "watchdesk-xpub",
      chain_id: 1,
      address_count: 5,
      funded_address_count: 1,
      native_total_wei_hex: eth("0"),
      signer_address_count: 0,
      watch_only_address_count: 5,
      erc20_holding_count: 2,
      nft_holding_count: 1,
      defi_holding_count: 0,
      claimable_holding_count: 0,
      approval_exposure_count: 0,
      dormant_candidate_count: 2,
    },
  ],
  routing: [
    {
      wallet_profile: "ops-seed",
      hot_address: ADDR.opsHot,
      treasury_address: ADDR.opsTreasury,
      default_destination_address: ADDR.opsTreasury,
      hot_native_balance_wei_hex: eth("0.218"),
      treasury_native_balance_wei_hex: eth("2.874"),
      routing_ready: true,
    },
    {
      wallet_profile: "treasury-seed",
      hot_address: null,
      treasury_address: ADDR.opsTreasury,
      default_destination_address: null,
      hot_native_balance_wei_hex: null,
      treasury_native_balance_wei_hex: eth("2.874"),
      routing_ready: false,
    },
  ],
  risk: { total_findings: 4, critical_findings: 0, high_findings: 1, medium_findings: 2, low_findings: 1 },
  plans: {
    total_plans: 1,
    latest_plan_id: "plan-20260715-a1",
    latest_plan_status: "review_required",
    latest_review_required_steps: 3,
    latest_approved_steps: 2,
    latest_executable_steps: 2,
    latest_blocked_steps: 1,
    policy_violations: [],
    latest_policy_violations: [],
  },
  receive: { active_allocations: 4, retired_allocations: 2, purposes: 3 },
  automation: { enabled: false, hot_overflow_wei_hex: null, generated_steps: 0, enqueued_steps: 0 },
};

export const parties = [
  {
    id: "party-acme",
    name: "Acme Ltd",
    note: "Monthly OTC settlement — invoice refs go in the allocation label.",
    sweep_destination_address: ADDR.acmeSweep,
    created_at_unix: NOW - 70 * D,
  },
  {
    id: "party-nakamoto",
    name: "Nakamoto Donor",
    note: "Recurring anonymous grant, pays in USDC on mainnet.",
    sweep_destination_address: null,
    created_at_unix: NOW - 44 * D,
  },
];

export const receiveAllocations = [
  {
    id: "alloc-01",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    chain_id: 1,
    address: ADDR.opsRecv0,
    derivation_path: "m/44'/60'/0'/0/0",
    address_index: 0,
    purpose: "invoice",
    label: "Acme 2026-07 invoice",
    status: "active",
    created_at_unix: NOW - 18 * D,
    retired_at_unix: null,
    counterparty_id: "party-acme",
  },
  {
    id: "alloc-02",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    chain_id: 1,
    address: ADDR.opsRecv1,
    derivation_path: "m/44'/60'/0'/0/1",
    address_index: 1,
    purpose: "invoice",
    label: "Acme 2026-06 invoice",
    status: "active",
    created_at_unix: NOW - 48 * D,
    retired_at_unix: null,
    counterparty_id: "party-acme",
  },
  {
    id: "alloc-03",
    wallet_family: "eth-xpub",
    wallet_profile: "watchdesk-xpub",
    chain_id: 1,
    address: ADDR.watch0,
    derivation_path: "m/44'/60'/2'/0/0",
    address_index: 0,
    purpose: "grant",
    label: "Nakamoto grant (watch-only)",
    status: "active",
    created_at_unix: NOW - 44 * D,
    retired_at_unix: null,
    counterparty_id: "party-nakamoto",
  },
  {
    id: "alloc-04",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    chain_id: 8453,
    address: ADDR.base0,
    derivation_path: "m/44'/60'/0'/0/0",
    address_index: 0,
    purpose: "operations",
    label: "Base ops float",
    status: "active",
    created_at_unix: NOW - 30 * D,
    retired_at_unix: null,
    counterparty_id: null,
  },
  {
    id: "alloc-05",
    wallet_family: "eth-seed",
    wallet_profile: "ops-seed",
    chain_id: 1,
    address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
    derivation_path: "m/44'/60'/0'/0/2",
    address_index: 2,
    purpose: "invoice",
    label: "Acme 2026-05 invoice",
    status: "retired",
    created_at_unix: NOW - 78 * D,
    retired_at_unix: NOW - 47 * D,
    counterparty_id: "party-acme",
  },
];

export const receivingOverview = {
  generated_at_unix: NOW - 60,
  include_retired: false,
  groups: [
    {
      counterparty: parties[0],
      item_count: 3,
      native_total_wei_hex: eth("1.234"),
      items: [
        {
          source_type: "hd",
          address: ADDR.opsRecv0,
          chain_id: 1,
          derivation_path: "m/44'/60'/0'/0/0",
          purpose: "invoice",
          label: "Acme 2026-07 invoice",
          counterparty_id: "party-acme",
          linkage_warning: null,
          balance_native_wei_hex: eth("0.842"),
          balance_known: true,
          status: "active",
          created_at_unix: NOW - 18 * D,
        },
        {
          source_type: "hd",
          address: ADDR.opsRecv1,
          chain_id: 1,
          derivation_path: "m/44'/60'/0'/0/1",
          purpose: "invoice",
          label: "Acme 2026-06 invoice",
          counterparty_id: "party-acme",
          linkage_warning: "address previously announced to Nakamoto Donor",
          balance_native_wei_hex: eth("0.392"),
          balance_known: true,
          status: "active",
          created_at_unix: NOW - 48 * D,
        },
        {
          source_type: "stealth",
          address: ADDR.stealthA,
          chain_id: 1,
          derivation_path: null,
          purpose: "stealth",
          label: "stealth payment",
          counterparty_id: "party-acme",
          linkage_warning: null,
          balance_native_wei_hex: eth("0.05"),
          balance_known: true,
          status: "observed",
          created_at_unix: NOW - 6 * D,
        },
      ],
    },
    {
      counterparty: parties[1],
      item_count: 1,
      native_total_wei_hex: eth("0"),
      items: [
        {
          source_type: "hd",
          address: ADDR.watch0,
          chain_id: 1,
          derivation_path: "m/44'/60'/2'/0/0",
          purpose: "grant",
          label: "Nakamoto grant (watch-only)",
          counterparty_id: "party-nakamoto",
          linkage_warning: null,
          balance_native_wei_hex: eth("0"),
          balance_known: true,
          status: "active",
          created_at_unix: NOW - 44 * D,
        },
      ],
    },
    {
      counterparty: null,
      item_count: 1,
      native_total_wei_hex: eth("0.0412"),
      items: [
        {
          source_type: "hd",
          address: ADDR.base0,
          chain_id: 8453,
          derivation_path: "m/44'/60'/0'/0/0",
          purpose: "operations",
          label: "Base ops float",
          counterparty_id: null,
          linkage_warning: null,
          balance_native_wei_hex: eth("0.0412"),
          balance_known: true,
          status: "active",
          created_at_unix: NOW - 30 * D,
        },
      ],
    },
  ],
  totals: { item_count: 5, hd_count: 4, stealth_count: 1, native_total_wei_hex: eth("1.2752") },
  coverage: {
    addresses_total: 5,
    addresses_with_known_balance: 5,
    note: "Balances refreshed from 2 provider(s) within the last 3 hours.",
  },
};

export const deposits = [
  {
    id: "dep-20260710-ax41",
    status: "observed",
    wallet_profile: "stealth-ops",
    asset_kind: "native",
    chain_id: 1,
    chain_id_assumed: false,
    wallet_compartment_id: 1,
    provider_compartment_id: 1,
    wallet: "ops-seed",
    short_name: "OPS-S",
    stealth_meta_address: STEALTH_META_ADDRESS,
    stealth_address: ADDR.stealthA,
    ephemeral_public_key_hex: "0x03a34b99f22c790c4e36b2b3c2c35a36db06226e41c692fc82b8b56ac1c540c5bd",
    view_tag_hex: "0x2a",
    stealth_hash_convention: "compressed33",
    announcement: {
      announcer_address: "0x55649E01B5Df198D18D95b5ad50587a0D1713407",
      metadata_hex: "0x01000000000000000000000000000000000000000000000000000000000000002a",
      calldata_hex: "0xa1b2c3d4e5f60718293a4b5c6d7e8f901122334455667788990aabbccddeeff00112233",
    },
    expected_amount_hex: eth("0.05"),
    observed_amount_hex: eth("0.05"),
    observed_native_balance_wei_hex: eth("0.05"),
    token_address: null,
    sweep_destination_address: ADDR.opsTreasury,
    min_sweep_amount_hex: null,
    auto_queue_sweep: true,
    queue_job_id: null,
    queue_job_state: null,
    created_at_unix: NOW - 6 * D,
    last_checked_at_unix: NOW - 3 * H,
    updated_at_unix: NOW - 3 * H,
    note: "Matches the Acme 2026-07 invoice amount.",
    broadcast_transaction_hash_hex: null,
    counterparty_id: "party-acme",
    requested_gas_wei_hex: null,
    gas_topup_job_id: null,
    gas_topup_job_state: null,
  },
  {
    id: "dep-20260713-bx07",
    status: "partial",
    wallet_profile: "stealth-ops",
    asset_kind: "erc20",
    chain_id: 1,
    chain_id_assumed: false,
    wallet_compartment_id: 1,
    provider_compartment_id: 1,
    wallet: "ops-seed",
    short_name: "OPS-S",
    stealth_meta_address: STEALTH_META_ADDRESS,
    stealth_address: ADDR.stealthB,
    ephemeral_public_key_hex: "0x02f9308a019258c31049344f85f89d5229b531c845836f99b08601f113bce036f9",
    view_tag_hex: "0x7c",
    stealth_hash_convention: "compressed33",
    announcement: {
      announcer_address: "0x55649E01B5Df198D18D95b5ad50587a0D1713407",
      metadata_hex: "0x0100000000000000000000000000000000000000000000000000000000000007c",
      calldata_hex: "0xdeadbeef0011223344556677889900aabbccddeeff0123456789abcdef00112233",
    },
    expected_amount_hex: tok("500.00"),
    observed_amount_hex: tok("250.00"),
    observed_native_balance_wei_hex: eth("0.0012"),
    token_address: ADDR.usdc,
    sweep_destination_address: ADDR.opsTreasury,
    min_sweep_amount_hex: tok("500.00"),
    auto_queue_sweep: false,
    queue_job_id: null,
    queue_job_state: null,
    created_at_unix: NOW - 3 * D,
    last_checked_at_unix: NOW - 90 * 60,
    updated_at_unix: NOW - 90 * 60,
    note: null,
    broadcast_transaction_hash_hex: null,
    counterparty_id: null,
    requested_gas_wei_hex: eth("0.005"),
    gas_topup_job_id: null,
    gas_topup_job_state: null,
  },
  {
    id: "dep-20260715-cx19",
    status: "announced",
    wallet_profile: "stealth-ops",
    asset_kind: "native",
    chain_id: 1,
    chain_id_assumed: false,
    wallet_compartment_id: 1,
    provider_compartment_id: 1,
    wallet: "ops-seed",
    short_name: "OPS-S",
    stealth_meta_address: STEALTH_META_ADDRESS,
    stealth_address: ADDR.stealthC,
    ephemeral_public_key_hex: "0x0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
    view_tag_hex: "0x91",
    stealth_hash_convention: "compressed33",
    announcement: null,
    expected_amount_hex: null,
    observed_amount_hex: "0x0",
    observed_native_balance_wei_hex: eth("0"),
    token_address: null,
    sweep_destination_address: ADDR.opsTreasury,
    min_sweep_amount_hex: null,
    auto_queue_sweep: true,
    queue_job_id: null,
    queue_job_state: null,
    created_at_unix: NOW - 20 * H,
    last_checked_at_unix: NOW - 20 * H,
    updated_at_unix: NOW - 20 * H,
    note: "Announcement seen, no value at the stealth address yet.",
    broadcast_transaction_hash_hex: null,
    counterparty_id: "party-nakamoto",
    requested_gas_wei_hex: null,
    gas_topup_job_id: null,
    gas_topup_job_state: null,
  },
  {
    id: "dep-20260628-px02",
    status: "swept",
    wallet_profile: "stealth-ops",
    asset_kind: "native",
    chain_id: 1,
    chain_id_assumed: false,
    wallet_compartment_id: 1,
    provider_compartment_id: 1,
    wallet: "ops-seed",
    short_name: "OPS-S",
    stealth_meta_address: STEALTH_META_ADDRESS,
    stealth_address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
    ephemeral_public_key_hex: "0x03b0bd634234abbb1ba1e986e884185c61cf43e001f9137f23c2c128273eb86e4c",
    view_tag_hex: "0x04",
    stealth_hash_convention: "compressed33",
    announcement: null,
    expected_amount_hex: eth("0.2"),
    observed_amount_hex: eth("0.2"),
    observed_native_balance_wei_hex: eth("0"),
    token_address: null,
    sweep_destination_address: ADDR.opsTreasury,
    min_sweep_amount_hex: null,
    auto_queue_sweep: true,
    queue_job_id: "job-20260628-s1",
    queue_job_state: "confirmed",
    created_at_unix: NOW - 18 * D,
    last_checked_at_unix: NOW - 17 * D,
    updated_at_unix: NOW - 17 * D,
    note: null,
    broadcast_transaction_hash_hex: "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060",
    counterparty_id: null,
    requested_gas_wei_hex: null,
    gas_topup_job_id: null,
    gas_topup_job_state: null,
  },
];

export const queueJobs = [
  {
    id: "job-20260716-q1",
    state: "queued",
    kind: "eth_stealth_native_sweep",
    wallet_profile: "stealth-ops",
    destination_address: ADDR.opsTreasury,
    attempts: 0,
    created_at_unix: NOW - 50 * 60,
    updated_at_unix: NOW - 50 * 60,
    next_attempt_after_unix: null,
    transaction_hash_hex: null,
    broadcast_transaction_hash_hex: null,
    receipt_status: null,
    confirmations: null,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: null,
  },
  {
    id: "job-20260716-q2",
    state: "queued",
    kind: "plan_step_execution",
    action: "sweep_native",
    plan_id: "plan-20260715-a1",
    step_id: "step-01",
    source_address: ADDR.opsRecv1,
    destination_address: ADDR.opsTreasury,
    prerequisite_job_ids: [],
    attempts: 0,
    created_at_unix: NOW - 45 * 60,
    updated_at_unix: NOW - 45 * 60,
    next_attempt_after_unix: null,
    transaction_hash_hex: null,
    broadcast_transaction_hash_hex: null,
    receipt_status: null,
    confirmations: null,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: null,
  },
  {
    id: "job-20260716-b1",
    state: "blocked",
    kind: "plan_step_execution",
    action: "sweep_erc20",
    plan_id: "plan-20260715-a1",
    step_id: "step-02",
    source_address: ADDR.opsRecv1,
    destination_address: ADDR.opsTreasury,
    token_address: ADDR.usdc,
    prerequisite_job_ids: ["job-20260716-q2"],
    attempts: 0,
    created_at_unix: NOW - 45 * 60,
    updated_at_unix: NOW - 45 * 60,
    next_attempt_after_unix: null,
    transaction_hash_hex: null,
    broadcast_transaction_hash_hex: null,
    receipt_status: null,
    confirmations: null,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: "waiting on prerequisite job job-20260716-q2",
  },
  {
    id: "job-20260716-r1",
    state: "retrying",
    kind: "eth_stealth_erc20_sweep",
    wallet_profile: "stealth-ops",
    token_address: ADDR.usdc,
    destination_address: ADDR.opsTreasury,
    attempts: 3,
    created_at_unix: NOW - 9 * H,
    updated_at_unix: NOW - 20 * 60,
    next_attempt_after_unix: NOW + 12 * 60,
    transaction_hash_hex: null,
    broadcast_transaction_hash_hex: null,
    receipt_status: null,
    confirmations: null,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: "provider error: HTTP 429 from base-mainnet.g.alchemy.com",
  },
  {
    id: "job-20260715-s1",
    state: "sent",
    kind: "plan_step_execution",
    action: "revoke_erc20_approval",
    plan_id: "plan-20260715-a1",
    step_id: "step-03",
    source_address: ADDR.opsRecv1,
    destination_address: null,
    prerequisite_job_ids: [],
    attempts: 1,
    created_at_unix: NOW - 7 * H,
    updated_at_unix: NOW - 22 * 60,
    next_attempt_after_unix: null,
    transaction_hash_hex: "0x88df016429689c079f3b2f6ad39fa052532c56795b733da78a62ebe2cb2e960a",
    broadcast_transaction_hash_hex: "0x88df016429689c079f3b2f6ad39fa052532c56795b733da78a62ebe2cb2e960a",
    receipt_status: null,
    confirmations: 0,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: null,
  },
  {
    id: "job-20260628-s1",
    state: "confirmed",
    kind: "eth_stealth_native_sweep",
    wallet_profile: "stealth-ops",
    destination_address: ADDR.opsTreasury,
    attempts: 1,
    created_at_unix: NOW - 18 * D,
    updated_at_unix: NOW - 17 * D,
    next_attempt_after_unix: null,
    transaction_hash_hex: "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060",
    broadcast_transaction_hash_hex: "0x5c504ed432cb51138bcf09aa5e8a410dd4a1e204ef84bfed1be16dfba1b22060",
    receipt_status: "success",
    confirmations: 14382,
    receipt_block_number: 22880012,
    receipt_gas_used_hex: "0x5208",
    last_error: null,
  },
  {
    id: "job-20260712-f1",
    state: "failed_terminal",
    kind: "eth_stealth_transfer",
    wallet_profile: "stealth-ops",
    to_address: "0x000000000000000000000000000000000000dEaD",
    attempts: 5,
    created_at_unix: NOW - 4 * D,
    updated_at_unix: NOW - 4 * D + 900,
    next_attempt_after_unix: null,
    transaction_hash_hex: null,
    broadcast_transaction_hash_hex: null,
    receipt_status: null,
    confirmations: null,
    receipt_block_number: null,
    receipt_gas_used_hex: null,
    last_error: "validation: destination 0x…dEaD is not in the policy allow-list",
  },
  {
    id: "job-20260714-o1",
    state: "operator_action_required",
    kind: "plan_step_execution",
    action: "sweep_erc20",
    plan_id: "plan-20260708-p9",
    step_id: "step-02",
    source_address: ADDR.opsRecv0,
    destination_address: ADDR.acmeSweep,
    token_address: ADDR.usdt,
    prerequisite_job_ids: [],
    attempts: 2,
    created_at_unix: NOW - 2 * D - 4 * H,
    updated_at_unix: NOW - 2 * D,
    next_attempt_after_unix: null,
    transaction_hash_hex: "0x1f4f0a00f29d5e57c9ba0e6f1d2c3b4a5968778695a4b3c2d1e0f9a8b7c6d5e4",
    broadcast_transaction_hash_hex: "0x1f4f0a00f29d5e57c9ba0e6f1d2c3b4a5968778695a4b3c2d1e0f9a8b7c6d5e4",
    receipt_status: "reverted",
    confirmations: 0,
    receipt_block_number: 22961200,
    receipt_gas_used_hex: "0xa410",
    last_error: "receipt discovered revert — review the step before re-queueing",
  },
];

// SelfCheckRunResponse: domains mirror crates/sigillum-daemon/src/service/selfcheck.rs
// (DOMAIN_* constants). One failing domain (provider) so the status strip,
// diag panel, and summary pills all exercise their trouble rendering.
export const selfCheckRun = {
  status: "fail",
  generated_at_unix: NOW - 15 * 60,
  checks: [
    { id: "provider:mainnet-llama", domain: "provider", subject: "mainnet-llama", status: "pass", detail: "eth_chainId returned 1; eth_blockNumber returned block 22970412.", latency_ms: 188 },
    { id: "provider:base-alchemy", domain: "provider", subject: "base-alchemy", status: "fail", detail: "HTTP 401 Unauthorized — the stored 'alchemy_base_key' was rejected by the endpoint.", latency_ms: 94 },
    { id: "seed-wallet:ops-seed", domain: "seed-wallet", subject: "ops-seed", status: "pass", detail: "Mnemonic secret decrypts; first receive address re-derives to 0x71C7656E…976F.", latency_ms: null },
    { id: "seed-wallet:treasury-seed", domain: "seed-wallet", subject: "treasury-seed", status: "pass", detail: "Mnemonic secret decrypts; first receive address re-derives to 0x8Ba1f109…Ba72.", latency_ms: null },
    { id: "xpub-wallet:watchdesk-xpub", domain: "xpub-wallet", subject: "watchdesk-xpub", status: "pass", detail: "Account xpub parses; receive branch derives index 0.", latency_ms: null },
    { id: "stealth-wallet:stealth-ops", domain: "stealth-wallet", subject: "stealth-ops", status: "pass", detail: "Wallet 'ops-seed' resolves; default destination is policy-allowed.", latency_ms: null },
    { id: "watch-book:vitalik.eth (reference)", domain: "watch-book", subject: "vitalik.eth (reference)", status: "pass", detail: "Address parses and is enabled.", latency_ms: null },
    { id: "policy:treasury", domain: "policy", subject: "treasury", status: "pass", detail: "3 allowed destinations configured; all plan destinations resolve.", latency_ms: null },
    { id: "receive-allocation:alloc-02", domain: "receive-allocation", subject: "Acme 2026-06 invoice", status: "warn", detail: "Address was previously announced to Nakamoto Donor — rotation recommended.", latency_ms: null },
    { id: "fido2:enrolled-keys", domain: "fido2", subject: "enrolled keys", status: "pass", detail: "2 keys enrolled; highest compartment threshold is 3.", latency_ms: null },
  ],
};

// DiagnosticsResponse in response.rs (the diag grid renders a subset).
export const diagnostics = {
  status: "ok",
  version: "1.0.0",
  unlock_scope: "compartment",
  session_scope: "browser-session",
  active_session_count: 1,
  unlocked_compartment_count: 1,
  max_unlocked_threshold: 2,
  default_active_compartment_id: 1,
  audit_log_present: true,
  pending_operation_count: 3,
  startup_interrupted_operation_count: 0,
  startup_recovered_operation_count: 1,
  startup_unresolved_operation_count: 0,
  queue_job_count: 8,
  blocked_queue_job_count: 1,
  retrying_queue_job_count: 1,
  failed_queue_job_count: 1,
  operator_action_required_queue_job_count: 1,
  deferred_queue_job_count: 0,
  startup_recovered_queue_job_count: 1,
  startup_reconciled_deposit_count: 2,
  runtime_policy: {
    queue_default_process_limit: 5,
    queue_max_process_limit: 25,
    deposit_default_refresh_limit: 10,
    deposit_max_refresh_limit: 100,
    queue_retry_base_delay_secs: 30,
    queue_retry_max_delay_secs: 1800,
    provider_balance_observation_concurrency: 4,
    audit_default_limit: 50,
    audit_max_limit: 500,
    receiving_refresh_address_cap: 64,
    idle_lock_secs: 900,
    idle_lock_drain_secs: 30,
    idle_lock_force_after_secs: 120,
  },
  eth_stealth_deposit_count: 4,
  funded_eth_stealth_deposit_count: 2,
  initialized: true,
  started_at_unix: NOW - 3 * D - 5 * H,
};

export const auditEvents = [
  { kind: "unlock.passphrase", compartment_id: 1, created_at_unix: NOW - 15 * 60, details: {} },
  { kind: "fido2.register", compartment_id: 1, created_at_unix: NOW - 2 * D - 3 * H, details: { label: "SoloKey 2 backup" } },
  { kind: "profiles.eth_seed_wallet.upsert", compartment_id: 1, created_at_unix: NOW - 4 * D, details: { name: "treasury-seed" } },
  { kind: "secret.set", compartment_id: 1, created_at_unix: NOW - 4 * D, details: { key: "treasury_seed_mnemonic" } },
  { kind: "api_key.set", compartment_id: 1, created_at_unix: NOW - 12 * D, details: { key: "alchemy_base_key" } },
  { kind: "compartment.init", compartment_id: null, created_at_unix: NOW - 40 * D, details: { label: "operations" } },
  { kind: "snapshot.export", compartment_id: 1, created_at_unix: NOW - 8 * D, details: {} },
  { kind: "unlock.fido2", compartment_id: 1, created_at_unix: NOW - 2 * D - 6 * H, details: {} },
];

export const fido2Detect = { device_present: true, device_count: 1 };
// Fido2StatusResponse in response.rs.
export const fido2Status = { enabled: true, key_count: 2 };
export const fido2Keys = {
  keys: [
    { label: "YubiKey 5C Nano", credential_id_short: "a1b2c3d4", registered_at: "2026-06-30 14:22" },
    { label: "SoloKey 2 backup", credential_id_short: "9f8e7d6c", registered_at: "2026-07-02 09:41" },
  ],
};

export const secretKeys = { keys: ["ops_seed_mnemonic", "treasury_seed_mnemonic", "safe_owner_note"] };
export const apiKeys = { keys: ["alchemy_base_key", "llama_mainnet_token"] };

export const nftOptIns = {
  opt_ins: [
    {
      chain_id: 1,
      contract_address: "0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85",
      enabled: true,
      created_at_unix: NOW - 30 * D,
      updated_at_unix: NOW - 30 * D,
    },
  ],
  ipfs_gateway_url: "https://ipfs.io",
};
